name: Workflow

on:
    push:
        branches: [main]

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: Hello Friends
              run: echo "Hey There!"

            - name: Hello User
              run: echo "Hello $USER"
