name: Workflow

on:
    push:
        branches: [main]

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: Hello Friends
              run: echo "Hey There!"

            - name: Hello User
              run: echo "Hello $USER"

    details:
        runs-on: ubuntu-latest
        steps:
            - name: Check if docker is installed or not
              run: docker --version  

            - name: check if python is installed or not
              run: python --version
